### PR TITLE
Relaxed the Plugin API constraint to ~1.0 so that the next version bump won't exclude this installer

### PR DESCRIPTION
**Pull request by nevvermind**

### CODE REVIEW

**Comment by Flyingmana** [comment]
I dont think thats how the API thing works. If I remember correctly this is used to define, which Version of the API we want to use.
I assume we need a new Release when this happens anyway.

Do you have any Link or Documentation regarding recent recommendations for this?

**Comment by nevvermind** [comment]
>this is used to define, which Version of the API we want to use.

Yes, but it can be a range, too. Why shouldn't your Plugin work with the `1.1.0` composer API?
https://getcomposer.org/doc/articles/plugins.md (it was changed recently)

>I assume we need a new Release when this happens anyway.

I suggest you get this PR _first_, not wait for a API bump. I have a PR now that, if accepted, will bump the Plugin API to `1.1.0`. If you leave the constraint fixed, your plugin won't be registered and no user with a new Composer version will be able to use it. If you relax its constraint, your users won't have surprises.

**Comment by Flyingmana** [comment]
I would rather expect to not have access to new API methods by using 1.0 instead of not being able to install. But having this in their documentation is reason enough for changing this.

**Comment by nevvermind** [comment]
> I would rather expect to not have access to new API methods by using 1.0 instead of not being able to install

You shouldn't expect that. You're requesting a _fixed version_ of a package (`1.0.0`). Composer complies, like for any other package. API changes doesn't mean only _new_ methods, it can also mean BC breaks. 
What's the purpose of requiring a `1.0.0` version, if Composer accepts it in - say - `2.0` and breaks your plugin?

**Comment by Flyingmana** [comment]
The purpose would be, so new plugins get executed in api2 context while old ones get executed in api1 context, so both can be used from plugins in parallel to grant backwards compatibility

**Comment by nevvermind** [comment]
What do you mean by "context"? And what happens if the `PluginInterface` changes in Composer 2.0?

**Comment by Flyingmana** [comment]
I have no idea, maybe magic or something like that. I dont remember many details from where it was introduced, but that it works different from packages.

I will ask when i meet one of the composer core contributors how the plans are today

**Pull request merged**
