### PR TITLE
add workaround for paths with containing whitespace

### PR DESCRIPTION
**Pull request by latenzio**

### CODE REVIEW

**Comment by AydinHassan** [comment]
Looks good to me :+1:

**Comment by latenzio** [comment]
@Flyingmana is there a release date for [3.0.6](https://github.com/Cotya/magento-composer-installer/tree/3.0.6)

**Comment by Flyingmana** [comment]
@latenzio I think wednsday is a good release day :)

**Comment by Flyingmana** [comment]
@latenzio https://github.com/Cotya/magento-composer-installer/releases/tag/3.0.6

**Comment by latenzio** [comment]
@Flyingmana you made my day :lollipop:

**Pull request merged**
