### PR TITLE
Remove version constraint from composer require statement in README.md

### PR DESCRIPTION
**Pull request by aadmathijssen**
Instead of using the asterisk (*), it is better to use the caret operator (^); see slides 50 to 68 of the [Composer the Right Way presentation from PHPBenelux16](http://www.slideshare.net/rdohms/composer-the-right-way-phpbnl16) by Rafael Dohms.

It is even better to not specify any version constraint, so Composer can determine the constraint automatically (using the caret operator).

### CODE REVIEW

**Comment by Flyingmana** [comment]
We have still a lot of people out there, who use the 2.x version branch, it may be worth for them to have a version string in the readme they can edit.

Also the ^ is not easy to understand for beginners(i needed months to see the actual benefit) while a wildcard is easy to understand for everyone.

But we can add a link to this talk in the readme for extended composer tutorials

**Comment by aadmathijssen** [comment]
I think you're right that it's better to have the version constraint in the README fir the 2.x users.

However, I do recommend replacing the asterisk syntax by the caret syntax to avoid accidental upgrades to preleases. E.g. when you create a release candidate tag 3.0.7-rc1, a composer update would update the package when using asterisk syntax but not when using caret syntax.

**Comment by Flyingmana** [comment]
you may not like it, but thats actually a good reason to keep it, there are way to few test users for such a release. Also the last times I had such a release, the installs had a total of 1-2...

**Comment by aadmathijssen** [comment]
Ah ok, then please ignore my PR :-)

**Pull request closed without merging**
