### PR TITLE
Create a new "extra" option flag to control patching of Mage.php (patching applied by default)

### PR DESCRIPTION
**Pull request by nevvermind**
This PR adds the new _boolean_  `extra` param - `with-bootstrap-patch` -, which can control if the `Mage.php` is changed/patched. 

If this param isn't found in `extra`, it'll be assumed `false` - hence no patching by default.

### CODE REVIEW

**Comment by nevvermind** [comment]
The `Bootstrap` was changed to have the `ProjectConfig` injected in the constructor, instead of the file path, as we need to check the config flag as well.

**Comment by Flyingmana** [comment]
Thank you very much for the patch, I will merge it later.
But, I will change the default.

I can fully understand, that there are people who absolutely dont want changes on magento core files.
But this changes usually dont cause harm and are an important base for coming features. Disabling them by default will reduce adoption rate so much, that I dont even need to work on them anymore, as most people dont read the documentation enough to activate them and other modules cant relay on them.

**Comment by nevvermind** [comment]
Sure, no problem. I was in doubt myself as to whether to leave it on or off. But yes, as future development is based on that flag being on, it's sensible to default it to that.

Let me do that change. I need to rename some of the test methods as well.

**Comment by Flyingmana** [comment]
will tag new releases on weekend, please ping me if I forget

**Pull request merged**
