### PR TITLE
Fixes for #7 and #33

### PR DESCRIPTION
**Pull request by unknownnf**
Add hasReference to check if an installed package has the right sourceReference.
Modify add function to also update installed packages, remove exception, it is only called if a package is added or updated.
Update InstalledPackage and InstalledPackageDumper to save and load new sourceReference variable.
Check and send source reference for installed/updated packages.
Fix tests for above changes.

Fixes issues #7 and #33.

### CODE REVIEW

**Comment by nevvermind** [comment]
Would you mind adding some tests to this?

**Comment by unknownnf** [comment]
I will, but I don't get the test structure yet and am out of time for now, will make a separate pr with hasReference and add tests. 

I've removed the obsolete test and modified the one throwing error where 'sourceReference' is returned as null.

**Comment by Flyingmana** [comment]
I merge it, and hope some tests come afterwards

**Comment by AydinHassan** [comment]
@unknownnf I don't understand why you have removed the exception? That function shouldn't be called twice with the same package. The add function is basically doing updating now. 

I think the old approach made more sense. If a package has been updated. First remove it then, because we want to remove all installed files. Then add it again, installing files again. I think this approach has complicated the code. Definitely needs tests also.

**Comment by nevvermind** [comment]
@AydinHassan - re the BC break: don't think it matters that much; how many packages depend on that interface? But, yes, it can break stuff.

Can somebody fill me in as to what this PR did? I think I understand the problem, but have you discussed the solution with @unknownnf? Was this reviewed? Why was it merged without tests? Was the documentation needed to be updated?

@Flyingmana - I would rather revert this PR until it's properly done and reviewed. The definition of "done" should include code, tests, changelog and documentation (if the case may be). Nothing less.

And it would be nice if every PR should get at least one +1 from a reviewer. I'd be suspicious if my PR had no comments at all.

@AydinHassan, would it be better to revert this PR to further a review about it?

**Comment by Flyingmana** [comment]
I had talked with @unknownnf via IRC about it, thats why there is no comment here.

the problem this patch fixes has to do with `dev-master` beeing internally a `9999999-dev` and so some compares dont work as expected. Therefore he makes use of SourceReference, which makes use of the internal vcs reference I think. He can probably answer this better then me.

I was ok with removing the exception, as there also was no real use/usecase for it yet, and I had the feeling it would produce more problems then helping currently.

I accepted the Patch without a Test, as it was obviously not easy to produce a working testcase, and prefer to merge a fix, then to wait another two weeks till a test is ready.

**Comment by nevvermind** [comment]
>I accepted the Patch without a Test, as it was obviously not easy to produce a working testcase, and prefer to merge a fix, then to wait another two weeks till a test is ready.

Why do you keep naming this "a fix"? :) 
How do you know that? Until tests arrive, it's only a _change_. Furthermore, if someone adds a new feature now, how would he/she test if it's not breaking this functionality?

The fact that this PR needs quite an effort to produce tests actually confirms that this is not a simple change; all the more reason _not_ to accept it lightly.

**Comment by Flyingmana** [comment]
I call it "a fix" as he had a problem he could reproduce which was fixed trough this patch.
Also this Patch did not break any existing tests/fullstack-tests.
The reasoning behind dev-master related issue means it is hard to reproduce automated, but not manually. Iam not even sure if it is possible to test this on full stack level with the current test framework we have.

**Comment by AydinHassan** [comment]
We can write a unit test for this easily, all we need to do us mock two packages. We can aldo do this without breaking BC (even though it doesn't really matter) and i'm pretty sure we can do this without complicating the code. I'm going to supply an alternate patch with tests later today. 

I agree that we shouldn't be accepting patches without tests. I don't want to sound like we are attacking @unknownnf, I appreciate his work. I just think this project seems to have a big impact on people's process, we should try harder to get it right.

**Pull request merged**
