### PR TITLE
Resolve package.xml mappings edge case

### PR DESCRIPTION
**Pull request by mikeymike**
* Replace double slashes in mappings

Sometimes dirs are mapped into empty dir tags
causing double slashes in the mapping.

### CODE REVIEW

**Comment by AydinHassan** [comment]
👍 We noticed this with a Fishpig extension from connect. 

The windows build seems to have 404'd when installing OpenSSL. @Flyingmana could you try restart the build to see if it was a one off?

**Comment by Flyingmana** [comment]
yeah, openssl got updated again... they always remove the old downloads. Will see what I can do about it.

Patch looks good besides that, will get merged after I fixied the windows CI

**Comment by AydinHassan** [comment]
Awesome, thanks 😀

**Comment by adragus-inviqa** [comment]
@mikeymike - Could you please add a changelog entry, too?

**Comment by mikeymike** [comment]
@adragus-inviqa I can do, but after reading the contributing.md this seemed to small of a change to warrant an entry in the changelog. @Flyingmana what do you think?

**Comment by Flyingmana** [comment]
an additional entry is always good for PRs, and it could affect something.
So feel free to add one.

Besides that, I will merge this PR on the weekend, even if the windows CI has not recovered

**Comment by Flyingmana** [comment]
windows CI is green, will merge after work :)

**Pull request merged**
