### PR TITLE
Update required PHP version

### PR DESCRIPTION
**Pull request by AydinHassan**

### CODE REVIEW

**Comment by Flyingmana** [comment]
any objections anyone?
If there are no in the next week I will merge it

**Comment by AydinHassan** [comment]
We should probably merge this now, as it does actually REQUIRE 5.4 atm. If we decide to support lower version, then we commit patches and then lower the requirement, but with the code base as is, it does only support >=5.4. By not committing this we are confusing our users, as seen in #43

**Comment by Flyingmana** [comment]
I tought more about if we maybe even go to require 5.5, as 5.4 is end of life next month.

Another possibility would be to many depend on 5.3, so we could not require a higher version

**Comment by AydinHassan** [comment]
I don't see the point of requiring `5.5` as we don't use `5.5` functionality.

**Comment by Flyingmana** [comment]
But we could

**Pull request merged**
