### PR TITLE
Replace windows path to unix path

### LINKED ISSUE #45: Invalid JSON written for magento-root-dir
I don't know if this still applies to the current version, just ran over it with a fresh composer install.

When the interactive installation routine asks for the magento installation directory that value is put into composer.json then.

This writing the input into composer.json is flawed. The input is not properly encoded as JSON value.

Enter character sequences like "c:\tmp\magento" for example, next time composer install is run you see errors:

```
 composer install



 [Seld\JsonLint\ParsingException]
 "./composer.json" does not contain valid JSON
 Parse error on line 17:
 ..."magento-root-dir": "c:\tmp\magento"
 ----------------------^
 Invalid string, it appears you have an unescaped backslash at: \m



nstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [
-no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
```

### PR DESCRIPTION
**Pull request by AydinHassan**
Should fix #45, not tested as I don't have a windows box

### CODE REVIEW

**Comment by AydinHassan** [comment]
@tkn98 I just saw this as the easier fix, sure we could escape the json properly, but does it really matter?

**Comment by tkn98** [comment]
@AydinHassan: Absolutely: You should never fix bugs on best guess and good luck, but by fixing the underlying issue, the actual flaw. At least I strongly suggest that. Otherwise you have not used the error properly and make it even harder to find it (cover it up instead of fixing it).

**Comment by tkn98** [comment]
@AydinHassan: But please the issue as well, I was not able to reproduce it today and it might be related to an older version.

**Comment by AydinHassan** [comment]
@tkn98 You are right, I was being lazy. Doesn't look like any code has been changed relating to the `composer.json` updating recently. Maybe something has changed in the actual `Composer` components which seem to be in use.

**Pull request closed without merging**
