### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tdgroot**
Minor version increase

### CODE REVIEW

**Comment by peterjaap** [comment]
Can you add quotes around it too to prevent zshrc and fish from trying to expand the *?

**Comment by peterjaap** [comment]
See #161

**Comment by tdgroot** [comment]
Ah, good catch. I updated it. 

Personally, I've disabled the zsh feature by adding the following to my `.zshrc`:
```
unsetopt nomatch
```

**Comment by tdgroot** [comment]
@Flyingmana Could you please review/merge this?

**Comment by Flyingmana** [comment]
sorry for it taking so long, sometimes this things slip trough.

**Comment by tdgroot** [comment]
Don't worry, thank you for merging!

**Pull request merged**
