### PR TITLE
WIP - Get tests running on Windows

### PR DESCRIPTION
**Pull request by AydinHassan**
This is a WIP - Do not merge yet.

Most of the issues with windows are to do with paths using different slashes everywhere. There are some nasty replaces everywhere to get this working. Once the tests are passing, we should re-visit this.

Some bugs with the fullstack tests include:
* Un-escaped paths in `composer.json`
* Artefacts not generating as the setup script was not locating composer properly
* Wrong paths

This is still not finished yet, however, the unit-tests are passing in Windows now, altough one test seems to have broken on Linux, I'll take a look at this later. 

Some of the full-stack tests are passing now. However I've got an issue with paths being too-long when composer extracts artefacts so I need to figure a way to make paths shorter. 

I need https://github.com/Cotya/composer-test-framework/pull/1 & https://github.com/Cotya/composer-test-framework/pull/2 merging also, as there are some bugs with Windows there.

### CODE REVIEW

**Comment by AydinHassan** [comment]
OK the unit tests are running on both Linux & Windows now

**Comment by AydinHassan** [comment]
@Flyingmana The Full Stack tests are broken in 3.0. See https://travis-ci.org/Cotya/magento-composer-installer/jobs/73970540. Seems like package `http://connect20.magentocommerce.com/community/AW_Blog/1.3.5/AW_Blog-1.3.5.tgz` is not available anymore. Is there any chance you could take a look at this? It seems the tests are always passing on Travis as it's using the cache. If you try run them locally on the `3.0` branch you should see them fail. 

I'm pretty sure you can fix it quicker than me, then I can re-base this branch and hopefully we are nearly there :)

**Comment by Flyingmana** [comment]
have added it hardcoded to the firegento repository
https://github.com/magento-hackathon/composer-repository/commit/72fdbc25d25950cd066e55ccc5a29f85144e45f6

hope that solves it

**Comment by AydinHassan** [comment]
Still not working, should I just wait longer?

**Comment by Flyingmana** [comment]
a bit more complicated then I tought, I will ping you as soon as it works

**Comment by AydinHassan** [comment]
ok thanks :)

**Comment by AydinHassan** [comment]
@Flyingmana Did you ever get the tests running?

**Comment by Flyingmana** [comment]
sadly no, also my new Windows PC I ordered never got to me (I probably should see that as a sign) so I could not even try it locally.

**Comment by AydinHassan** [comment]
What seems to be wrong then? I'm talking about the tests on Linux btw, not this PR her.  What changed? I know there was an issue with one of the packages we used in the full stack tests being removed from connect, but I thought that was fixed?

**Comment by Flyingmana** [comment]
Ahh right, I remember.

I was not able to Patch around it.
then I waited till firegento made a new import of the connect packages.

It did not fix by itself, and it seems the connect packages changed something internal, so the package xml references files, which dont exist anymore. And as the mapping is generated from this xml, they cant deploy anymore. And I have no Idea how to fix it, besides removing any connect packages from the fullstack tests

**Pull request closed without merging**
